// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB89sDa1aqYloCz3HX4oWc7YZLMBFAPpN4',
    appId: '1:714719323581:web:29b20e3da70b55b8655ed4',
    messagingSenderId: '714719323581',
    projectId: 'universidades-f230b',
    authDomain: 'universidades-f230b.firebaseapp.com',
    storageBucket: 'universidades-f230b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIHJwHc_97vvasFbO_giDMJgP8BFCTe7w',
    appId: '1:714719323581:android:1bcd3aa42562c913655ed4',
    messagingSenderId: '714719323581',
    projectId: 'universidades-f230b',
    storageBucket: 'universidades-f230b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG4_WWXrYGByM0DLwvEn26NQY1lElTs78',
    appId: '1:714719323581:ios:3a5f186c9ac1ade4655ed4',
    messagingSenderId: '714719323581',
    projectId: 'universidades-f230b',
    storageBucket: 'universidades-f230b.firebasestorage.app',
    iosBundleId: 'com.example.talleresMoviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG4_WWXrYGByM0DLwvEn26NQY1lElTs78',
    appId: '1:714719323581:ios:3a5f186c9ac1ade4655ed4',
    messagingSenderId: '714719323581',
    projectId: 'universidades-f230b',
    storageBucket: 'universidades-f230b.firebasestorage.app',
    iosBundleId: 'com.example.talleresMoviles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB89sDa1aqYloCz3HX4oWc7YZLMBFAPpN4',
    appId: '1:714719323581:web:11f656fab88c304e655ed4',
    messagingSenderId: '714719323581',
    projectId: 'universidades-f230b',
    authDomain: 'universidades-f230b.firebaseapp.com',
    storageBucket: 'universidades-f230b.firebasestorage.app',
  );
}
